#!/bin/bash
#############################################################################
gls_x_z_usage () {
printf "%s" "\
usage: gls x z [-h]

  Test x-z.  More documentation.

options:

  -h  prints help

"
}
while getopts "h" option
do
  case $option in
    (h)  gls_x_z_usage
         exit 0 ;;
    (*)  gls_x_z_usage | head -n 1
         exit 2 ;;
  esac
done
#############################################################################

printf "x-z\n"
