#!/bin/bash
#############################################################################
gls_xx_yy_usage () {
printf "%s" "\
usage: gls xx yy [-h]

  Test xx-yy.  More documentation.

options:

  -h  prints help

"
}
while getopts "h" option
do
  case $option in
    (h)  gls_xx_yy_usage
         exit 0 ;;
    (*)  gls_xx_yy_usage | head -n 1
         exit 2 ;;
  esac
done
#############################################################################

printf "xx-yy\n"
