#!/bin/bash
#############################################################################
gls_a_b_usage () {
printf "%s" "\
usage: gls a b [-h]

  Test a-b.  More documentation.

options:

  -h  prints help
"
}
while getopts "h" option
do
  case $option in
    (h)  gls_a_b_usage
         exit 0 ;;
    (*)  gls_a_b_usage | head -n 1
         exit 2 ;;
  esac
done
#############################################################################
export GLS_TEST_A_B=a_b
export GLS_TEST_A_B_C_ENV=a_b
export GLS_TEST_A_B_C=a_b

if [ $# -eq 0 ]
then gls_test_env
else gls_exec "$@"
fi
