#!/bin/bash
#############################################################################
gls_a_b_c_usage () {
printf "%s" "\
usage: gls a b c [-h]

  Test a-b-c.  More documentation.

options:

  -h  prints help
"
}
while getopts "h" option
do
  case $option in
    (h)  gls_a_b_c_usage
         exit 0 ;;
    (*)  gls_a_b_c_usage | head -n 1
         exit 2 ;;
  esac
done
#############################################################################
export GLS_TEST_A_B_C=a_b_c

gls_test_env
