#!/bin/bash
#############################################################################
gls_x_y_usage () {
printf "%s" "\
usage: gls x y [-h]

  Test x-y.  More documentation.

options:

  -h  prints help

"
}
while getopts "h" option
do
  case $option in
    (h)  gls_x_y_usage
         exit 0 ;;
    (*)  gls_x_y_usage | head -n 1
         exit 2 ;;
  esac
done
#############################################################################

printf "x-y\n"
