#!/bin/bash
#############################################################################
elastic_cluster_usage () {
printf "%s" "\
usage: elastic cluster [-h] QUERY_NAME

  Get cluster information.

options:

  -h          prints help
  -l          list cluster endpoints
  -p          preview requests
  -v          verbose output

"
}
args=""
while [ $OPTIND -le $# ]
do
  if getopts "hlpv" option
  then
    case $option in
      (h) elastic_cluster_usage
          exit 0 ;;
      (l) elastic-api get "_cat" | sed -ne 's|/_cat/||p'
          exit 0 ;;
      (p) preview="true";;
      (v) verbose="true";;
      (*) elastic_cluster_usage | head -n 1
          exit 2 ;;
    esac
  else
    args="$args \"\${$OPTIND}\""
    OPTIND=$(($OPTIND + 1))
  fi
done
eval set -- "$args"

verbose="${verbose:-}"
#############################################################################

for query in "$@"
do
  # something is wrong here... why is elastic-api needed?
  elastic-api get ${preview:+-p} "_cat/${query}?${verbose:+v}"
done
