#!/bin/bash
gls_basic_api_domain="$GITHUB_DOMAIN"
gls_basic_api_token_file="$GITHUB_TOKEN_FILE"

gls_basic_api_fetch_token_unencoded () {
  username=$1; password=$2; domain=$3;
  shift 3

  printf "2-factor code (empty unless needed): " >&2
  read otp_code

  if [ -n "$otp_code" ]
  then otp_header="-H X-GitHub-OTP:$otp_code"
  else otp_header=""
  fi

  json="$(curl -s -d '{"scopes":["repo"],"note":"github api token on $HOSTNAME"}' -u "$username:$password" ${otp_header} "https://$domain/authorizations")"
  token="$(printf "%s\n" "$json" | sed -ne 's/[[:space:]]*"token": "\([[:xdigit:]]*\)".*/\1/p')"
  
  if [ -z "$token" ]
  then printf "%s\n" "$json" >&2
  fi

  printf "%s\n" "$token"
}

. gls_basic_api
